name: "DogeOps : Build Docker image"

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        required: false
        type: string
        default: ubuntu-latest
      project-folder:
        description: The folder containing the project to build
        required: false
        type: string
        default: .

      # -----------------------
      container_registry:
        description: "defaults to GitHub Container Registry (ex: docker.io)"
        required: false
        type: string
        default: 'ghcr.io'
      container_repository:
        description: "in case of Docker Hub: username/image-name"
        required: false
        type: string
        default: ''
    secrets:
      container_registry_username:
        description: 'Username for container registry'
        required: false
      container_registry_password:
        description: 'Password for container registry'
        required: false

jobs:
  build:
#    defaults:
#      run:
#        working-directory: ${{ inputs.project-folder }}
    permissions:
      contents: read
      packages: write  # Push
    runs-on: ${{ inputs.runs-on }}
    steps:
    - uses: actions/checkout@v3
    - name: Get repository accesses
      id: get-repo
      run: |
        REPO=""
        USERNAME=""
        PASSWORD=""
        if [ ${{ inputs.container_registry }} = 'ghcr.io' ]; then
          REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          USERNAME=${{ github.actor }}
          PASSWORD=${{ secrets.GITHUB_TOKEN }}
        else
          REPO=${{ inputs.container_repository }}
          USERNAME=${{ secrets.container_registry_username }}
          PASSWORD=${{ secrets.container_registry_password }}
        fi
        if [ ${{ inputs.project-folder }} != '.' ]; then
          REPO_SFX=${{ inputs.project-folder }}-
          echo "suffixed $REPO$REP_SFX"
        fi

        echo "::set-output name=repo::$REPO"
        echo "::set-output name=username::$USERNAME"
        echo "::set-output name=password::$PASSWORD"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.container_registry }}
        username: ${{ steps.get-repo.outputs.username }}
        password: ${{ steps.get-repo.outputs.password }}

    - name: Generate tags and image meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
           ${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}
        tags: |
          type=ref,event=tag
          type=sha

    - name: debug
      run: |
        pwd
        cd ..
        ls -laRt

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.project-folder }}
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:latest
        cache-to: type=registry,ref=${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:latest,mode=max

    - name: Analyze image efficiency
      uses: MartinHeinz/dive-action@v0.1.3
      with:
        image: '${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:${{ steps.meta.outputs.version }}'
        config: ${{ inputs.DIVE_CONFIG }}
        exit-zero: ${{ !inputs.ENFORCE_DIVE }}

    # The results of this scan should be pushed to GH security, but that's not free
    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      id: image-scan
      with:
        image-ref: '${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:${{ steps.meta.outputs.version }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Push container image
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.project-folder }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=registry,ref=${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:latest
        cache-to: type=registry,ref=${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:latest,mode=max

    - name: Sign the published image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign ${{ inputs.container_registry }}/${{ steps.get-repo.outputs.repo }}:${{ steps.meta.outputs.version }}