name: 'DogeOps : Project Changed'

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        required: false
        type: string
        default: 'ubuntu-latest'
      project-folder:
        description: The folder containing the project to build
        type: string
        required: false
        default: .


jobs:
  project-changed:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.project-folder }}
    outputs:
      changed: ${{ steps.changes.outputs.src }}

    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        list-files: shell
        filters: |
          src:
            - "${{ inputs.project-folder }}/**"
